import UserIcon from "./UserIcon.jpeg"
import CurrentVehicle from "./CurrentVehicle.png"
import ReplacementVehicle from "./ReplacementVehicle.png"
import Faqs from "./faqs.png"
import Talks from "./talks.png"
import Summary from "./summary.png"
import Strategy from "./Strategy.jpg"
import Discuss from "./Discuss.png"
import User from "./User.png"
export default {UserIcon,CurrentVehicle,ReplacementVehicle,Faqs,Talks, Summary, Strategy, Discuss, User}